version: '3.5'

services:

  app:
    container_name: my-app
    build: ./
    volumes:
      - .:/app
    links:
      - db
      - redis
    ports:
      - "7777"
    env_file: ./.env
    environment:
      "NODE_ENV": "local"
    networks:
      - app-network

  db:
    env_file: ./.env
    image: mysql/mysql-server:latest
    container_name: mysql_node
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_USERNAME}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
